// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	demo "hertz.demo/biz/router/demo"
	gateway "hertz.demo/biz/router/gateway"
	teacher "hertz.demo/biz/router/teacher"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	teacher.Register(r)

	gateway.Register(r)

	demo.Register(r)
}
