// Code generated by hertz generator.

package gateway

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _addserviceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteserviceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getserviceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listserviceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateserviceMw() []app.HandlerFunc {
	// your code...
	return nil
}
