// Code generated by hertz generator.

package teacher

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/cloudwego/kitex/client/genericclient"
	"hertz.demo/biz/clientprovider"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	teacher "hertz.demo/biz/model/teacher"
)

// Query .
// @router /get-teacher-info [POST]
func Query(ctx context.Context, c *app.RequestContext) {
	var err error
	var req teacher.QueryReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	jsonReq, err := json.Marshal(req)
	if err != nil {
		fmt.Println("error:", err)
	}
	fmt.Println("jsonReq:", string(jsonReq))

	// 泛化调用
	cli := clientprovider.GetGenericClient("teacher-server").(genericclient.Client)
	resp, err := cli.GenericCall(ctx, "Query", string(jsonReq))

	c.JSON(consts.StatusOK, resp)
}
